package com.example.oliverh.bakerapp.data.database;

import android.arch.persistence.room.ColumnInfo;
import android.arch.persistence.room.Entity;
import android.arch.persistence.room.ForeignKey;
import android.arch.persistence.room.PrimaryKey;

import static android.arch.persistence.room.ForeignKey.CASCADE;

@Entity(foreignKeys = @ForeignKey(entity = Recipe.class,
        parentColumns = "id",
        childColumns = "recipe_id",
        onDelete = CASCADE))
public class RecipeStep {

    //  The following two properties need clarification.
    //      mRecipeStepId or recipe_step_id is the autogenerated "UNIQUE" PrimaryKey
    //      required by Room.
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "recipe_step_id")
    private int mRecipeStepId;

    //  mStepIndex or recipe_step_index refers to the instruction step index.
    //      The step ids found in the raw JSON file imply that the order of the recipe instructions
    //      and the id progression are the same.
    @ColumnInfo(name = "recipe_step_index")
    private int mStepIndex;

    @ColumnInfo(name = "recipe_id")
    private int mRecipeId;

    @ColumnInfo(name = "short_description")
    private String mShortDescription;

    @ColumnInfo(name = "description")
    private int mDescription;

    @ColumnInfo(name = "video_url")
    private String mVideoUrl;

    @ColumnInfo(name = "thumbnail_url")
    private String mThumbnailUrl;
}
