package com.example.oliverh.bakerapp.data.database;

import android.arch.persistence.room.ColumnInfo;
import android.arch.persistence.room.Entity;
import android.arch.persistence.room.ForeignKey;
import android.arch.persistence.room.PrimaryKey;

import static android.arch.persistence.room.ForeignKey.CASCADE;

@Entity(foreignKeys = @ForeignKey(entity = Recipe.class,
        parentColumns = "id",
        childColumns = "recipe_id",
        onDelete = CASCADE))
public class RecipeIngredient {
    //  The following property needs clarification.
    //      recipeIngredientId or recipe_ingredient_id is the autogenerated "UNIQUE" PrimaryKey
    //      required by Room.
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "recipe_ingredient_id")
    private int recipeIngredientId;

    @ColumnInfo(name = "recipe_id")
    private int recipeId;

    private String ingredient;
    private int quantity;

    @ColumnInfo(name = "measurement")
    private String measure;


    public RecipeIngredient(int recipeIngredientId, int recipeId, int quantity, String measure, String ingredient) {
        this.recipeIngredientId = recipeIngredientId;
        this.recipeId = recipeId;
        this.quantity = quantity;
        this.measure = measure;
        this.ingredient = ingredient;
    }

    public int getRecipeIngredientId() {
        return recipeIngredientId;
    }

    public void setRecipeIngredientId(int mRecipeIngredientId) {
        this.recipeIngredientId = mRecipeIngredientId;
    }

    public int getRecipeId() {
        return recipeId;
    }

    public void setRecipeId(int recipeId) {
        this.recipeId = recipeId;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int mQuantity) {
        this.quantity = mQuantity;
    }

    public String getMeasure() {
        return measure;
    }

    public void setMeasure(String measure) {
        this.measure = measure;
    }

    public String getIngredient() {
        return ingredient;
    }

    public void setIngredient(String mIngredient) {
        this.ingredient = mIngredient;
    }
}
