package com.example.oliverh.bakerapp.data.database;

import android.arch.persistence.room.ColumnInfo;
import android.arch.persistence.room.Entity;
import android.arch.persistence.room.ForeignKey;
import android.arch.persistence.room.Ignore;
import android.arch.persistence.room.Index;
import android.arch.persistence.room.PrimaryKey;

import java.util.Locale;

import static android.arch.persistence.room.ForeignKey.CASCADE;

@Entity(foreignKeys = @ForeignKey(entity = Recipe.class,
            parentColumns = "id",
            childColumns = "recipe_id",
            onDelete = CASCADE),
        indices = {@Index("recipe_id")})
public class RecipeIngredient {
    //  The following property needs clarification.
    //      recipeIngredientId or recipe_ingredient_id is the autogenerated "UNIQUE" PrimaryKey
    //      required by Room.
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "recipe_ingredient_id")
    private transient int recipeIngredientId;

    @ColumnInfo(name = "recipe_id")
    private transient int recipeId;

    private String ingredient;
    private double quantity;

    @ColumnInfo(name = "measurement")
    private String measure;

    @Ignore
    @SuppressWarnings("unused")
    public RecipeIngredient() {}

    public RecipeIngredient(int recipeIngredientId, int recipeId, double quantity, String measure, String ingredient) {
        this.recipeIngredientId = recipeIngredientId;
        this.recipeId = recipeId;
        this.quantity = quantity;
        this.measure = measure;
        this.ingredient = ingredient;
    }

    public int getRecipeIngredientId() {
        return recipeIngredientId;
    }

    public void setRecipeIngredientId(int mRecipeIngredientId) {
        this.recipeIngredientId = mRecipeIngredientId;
    }

    public int getRecipeId() {
        return recipeId;
    }

    public void setRecipeId(int recipeId) {
        this.recipeId = recipeId;
    }

    public double getQuantity() {
        return quantity;
    }

    public void setQuantity(double mQuantity) {
        this.quantity = mQuantity;
    }

    public String getMeasure() {
        return measure;
    }

    public void setMeasure(String measure) {
        this.measure = measure;
    }

    public String getIngredient() {
        return ingredient;
    }

    public void setIngredient(String mIngredient) {
        this.ingredient = mIngredient;
    }

    @Override
    public String toString() {
        String compiled = String.format(Locale.ENGLISH, "RecipeId: %d, Ingredient: %s, Quantity: %.2f, Measurement: %s", recipeId, ingredient, quantity, measure);
        return compiled;
    }
}
